vpc_name: "infraworkshop-apne2"
cidr_block: "192.168.10.0/24"
nat_security_group_name: "infraworkshop-apne2-permit-nat-security-group"
subnets: 
  infraworkshop-apne2-public-subnet-a:
    availability_zone: "ap-northeast-2a"
    cidr_block: "192.168.10.0/26"
  infraworkshop-apne2-public-subnet-c:
    availability_zone: "ap-northeast-2c"
    cidr_block: "192.168.10.64/26"
  infraworkshop-apne2-private-subnet-a:
    availability_zone: "ap-northeast-2a"
    cidr_block: "192.168.10.128/27"
    nat_gateway_subnet: "infraworkshop-apne2-public-subnet-a"
  infraworkshop-apne2-private-subnet-c:
    availability_zone: "ap-northeast-2c"
    cidr_block: "192.168.10.160/27"
    nat_gateway_subnet: "infraworkshop-apne2-public-subnet-a"
security_groups:
  infraworkshop-apne2-external-permit-security-group: null
  infraworkshop-apne2-internal-permit-security-group: null
  infraworkshop-apne2-permit-nat-security-group: null
ingress_rules:
  infraworkshop-apne2-external-permit-https-security-group-allow-443:
    security_group_name: "infraworkshop-apne2-external-permit-security-group"
    cidr_ipv4: "0.0.0.0/0"
    from_port: 443
    ip_protocol: "tcp"
    to_port: 443
  infraworkshop-apne2-external-permit-ssh-security-group-allow-managed-22:
    security_group_name: "infraworkshop-apne2-external-permit-security-group"
    cidr_ipv4: "192.168.10.160/27"
    from_port: 22
    ip_protocol: "tcp"
    to_port: 22
  infraworkshop-apne2-internal-permit-mysql-security-group-allow-3306:
    security_group_name: "infraworkshop-apne2-internal-permit-security-group"
    cidr_ipv4: "192.168.10.0/26"
    from_port: 3306
    ip_protocol: "tcp"
    to_port: 3306
  infraworkshop-apne2-internal-permit-ssh-security-group-allow-managed-22:
    security_group_name: "infraworkshop-apne2-internal-permit-security-group"
    cidr_ipv4: "192.168.10.160/27"
    from_port: 22
    ip_protocol: "tcp"
    to_port: 22
  infraworkshop-apne2-permit-nat-security-group-allow-vpc-cidr:
    security_group_name: "infraworkshop-apne2-permit-nat-security-group"
    cidr_ipv4: "192.168.10.0/24"
    ip_protocol: "-1"
egress_rules:
  infraworkshop-apne2-external-permit-all-security-group-allow-permit:
    security_group_name: "infraworkshop-apne2-external-permit-security-group"
    cidr_ipv4: "0.0.0.0/0"
    ip_protocol: "-1"
  infraworkshop-apne2-internal-permit-all-security-group-allow-permit:
    security_group_name: "infraworkshop-apne2-internal-permit-security-group"
    cidr_ipv4: "0.0.0.0/0"
    ip_protocol: "-1"
  infraworkshop-apne2-permit-nat-security-group-allow-vpc-cidr:
    security_group_name: "infraworkshop-apne2-permit-nat-security-group"
    cidr_ipv4: "0.0.0.0/0"
    ip_protocol: "-1"